nosana:
  description: Python Tests

global:
  image: python:3.10

jobs:
  - name: Install dependencies
    commands:
      # Initialize
      - curl -sS https://sh.rustup.rs | sh -s -- -y
      - . "$HOME/.cargo/env"
      - pip install .[dev] -t ./packages
      - ls -all
    artifacts:
      - name: packages

  - name: Check Python Entrypoint
    commands: 
      - python -c "import nucypher; print(nucypher.__version__)"
    resources:
      - name: packages
  
  ## Tests
  ## - name: Unit Tests (Coverage)
  ##   commands: 
     ##  - export PYTHONPATH=./packages
##       - python -m coverage run --data-file=unit_data -m pytest tests/unit
  ##     - python -m coverage xml -i --data-file=unit_data -o unit-coverage.xml
##     resources:
   ##    - name: packages

##   - name: Integration Tests (Coverage)
   ##  commands: 
      ## - export PYTHONPATH=./packages
##       - python -m coverage run --data-file=integration_data -m pytest tests/integration
##       - python -m coverage xml -i --data-file=integration_data -o integration-coverage.xml
   ##  resources:
      ## - name: packages
  - name: Agents Tests (Coverage)
    commands:
      # - export PYTHONPATH=./packages
      - cd ./tests/acceptance
      - export PYTHONPATH=../../packages
      - python -m coverage run --data-file=acceptance_agent_data -m pytest agents
      - python -m coverage xml -i --data-file=acceptance_agent_data -o acceptance-agents-coverage.xml
    resources:
      - name: packages
           
  - name: Upload to Codecov
    commands:
      - curl -Os https://uploader.codecov.io/latest/linux/codecov
      - chmod +x codecov
      - echo $CODECOV_TOKEN
      - ./codecov -t $CODECOV_TOKEN
    resources:
      - name: packages   
      
  