nosana:
  description: p Python Tests

global:
  image: python:3.10

jobs:
  - name: Install dependencies
    commands:
      # Initialize
      - curl -sS https://sh.rustup.rs | sh -s -- -y
      - . "$HOME/.cargo/env"
      - pip install .[dev] -t ./packages
      - ls -all
    artifacts:
      - name: packages
  - name: Check CLI Entrypoint
    commands: 
      - export PYTHONPATH=./packages
      - nucypher --help
    resources:
      - name: packages

  - name: Check Python Entrypoint
    commands: 
      - python -c "import nucypher; print(nucypher.__version__)"
    resources:
      - name: packages
  
  ## Tests
  - name: Unit Tests (Coverage)
    commands: 
      - export PYTHONPATH=./packages
      - coverage run --data-file=unit_data -m pytest tests/unit
      - coverage xml -i --data-file=unit_data -o unit-coverage.xml
    resources:
      - name: packages

  - name: Integration Tests (Coverage)
    commands: 
      - export PYTHONPATH=./packages
      - coverage run --data-file=integration_data -m pytest tests/integration
      - coverage xml -i --data-file=integration_data -o integration-coverage.xml
    resources:
      - name: packages
      
  - name: Agents Tests (Coverage)
    commands: 
      - export PYTHONPATH=./packages
      - coverage run --data-file=acceptance_agent_data -m pytest agents
      - coverage xml -i --data-file=acceptance_agent_data -o acceptance-agents-coverage.xml
    resources:
      - name: packages
