nosana:
  description: p Python Tests

global:
  image: python:3.10

jobs:
  - name: Install dependencies
    commands:
      # Initialize
      - curl https://sh.rustup.rs -sSf | sh -y
      - python -m pip install --upgrade pip
      - pip install .[dev]
    artifacts:
      - name: site-packages

  - name: Check CLI Entrypoint
    commands:
      - nucypher --help
    resources:
      - name: site-packages
  - name: Check Python Entrypoint
    commands: 
      - python -c "import nucypher; print(nucypher.__version__)"
    resources:
      - name: site-packages
