nosana:
  description: p Python Tests

global:
  image: python:3.10

jobs:
  - name: Install dependencies
    commands:
      # Initialize
      - curl -sS https://sh.rustup.rs | sh -s -- -y
      - . "$HOME/.cargo/env"
      - pip install .[dev] -t ./packages
      - ls -all
    artifacts:
      - name: packages
  - name: Check Python Entrypoint
    commands: 
      - python -c "import nucypher; print(nucypher.__version__)"
    resources:
      - name: packages
  - name: Unit Tests (Coverage)
    commands: 
      - export PYTHONPATH=./packages
      - python -m coverage run --data-file=unit_data -m pytest tests/unit
      - python -m coverage xml -i --data-file=unit_data -o unit-coverage.xml
    resources:
      - name: packages
